config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get     'signup',        to: 'users#new'
  get     'login',         to: 'sessions#new'
  post    'login',         to: 'sessions#create'
  delete  'logout',        to: 'sessions#destroy'
  get     'get_image/:id', to: 'images#get_image'

  resources :users
  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :google_id,presence: true
  validates :comment, length: { maximum: 300 }
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    validates :name, presence: true, length: { maximum: 10 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :images
    
    def list_items
        images.where(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include ImagesHelper
    before_action :logged_in_user
    
    def new
    end
    
    def create
        file = params[:file]
        if  (file != nil) &&  (file.content_type == "image/jpeg" || file.content_type =="image/jpg")
          
          
          exif = EXIFR::JPEG.new(file.tempfile)
          if is_exif?(exif)
            image_meta = image_meta(exif)
          else
            flash[:danger] = "必要なexif情報がありません。緯度経度、撮影日時を入力してください"
            redirect_to action: 'new' and return
          end
          uploadfile = upload_file(file)

          @image = Image.new
          @image.attributes ={  user_id:      current_user.id,
                                google_id:    uploadfile.id,
                                latitude:     image_meta[:latitude] ,
                                longitude:    image_meta[:longitude], 
                                address:      image_meta[:address], 
                                full_address: image_meta[:full_address]}
          
          if @image.save
            flash[:success] = "画像を登録しました"
            redirect_to current_user
          else 
            @google_file= google_auth_session.file_by_id(@image[:id])
            flash[:danger] = "登録に失敗しました"
            redirect_to :action =>"new"
          end
        else
          flash[:danger] = 'アップロードする画像はjpegかjpeg形式でお願いします。'
          redirect_to :action =>"new"
        end
    end

    def show
      @show_file = Image.find_by(id: params[:id])
    end
    
    
    def get_image
      file = Image.find_by(id: params[:id])       
      if file.user_id != current_user.id
        redirect_to current_user
      end
      
      file = download_file(file)
      send_data file, type: "image/jpg", disposition: :inline  
    end
    
    def edit
      @edit_file = Image.find_by(id: params[:id])
    end
    
    def update
      @update_file = Image.find_by(id: params[:id])
      @image = params.require(:image).permit(:comment)
      if @update_file.update(@image)
      
        redirect_to @update_file
      else
        render 'edit'
      end
    end
      
  
    def destroy
      @delete_file = Image.find_by(id: params[:id])
      
      #Googleドライブから削除
      delete_file(@delete_file)
      
      @drive_file.destroy
      flash[:success] = "Image Deleted"
      redirect_to current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash.now[:danger] = 'メールアドレスかパスワードが間違っています。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    include ImagesHelper

  def home
    @user = current_user
    if(@user==nil)
      redirect_to login_url
    elsif
      @images = current_user.list_items
      @google_images = google_auth_session.files
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include ImagesHelper
    before_action :logged_in_user, only: [:show, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ようこそ! #{@user.name}"
      redirect_to @user
    else
      flash.now[:alert] = "新規会員登録に失敗しました"
      render 'new'
    end
  end
    
  def show
    @user = User.find(params[:id])
    @images = @user.list_items
    @google_images = file_list
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
    
    # Oauth認証する
    def google_auth_session
        client = Google::APIClient.new
        
        auth = client.authorization
        auth.client_id = ENV["CLIENT_ID"] # 「クライアントID」の文字列
        auth.client_secret = ENV["CLIENT_SECRET"] # 「クライアントシークレット」の文字列
        auth.refresh_token = ENV["REFRESH_TOKEN"]
        auth.fetch_access_token!

        @session = GoogleDrive.login_with_oauth(client)
    end
    
    # ファイル一覧を取得
    def file_list
        @list = google_auth_session.files
    end
    
    # 画像をアップロードする
    def upload_file(file)
        @file = google_auth_session.upload_from_file(file.tempfile, file.original_filename, convert: false)
    end
    
    # google_idから画像を特定する
    def find_file(file)
        @file = google_auth_session.file_by_id(file.google_id)
    end
    
    # google_idから画像を特定し、画像を削除する。
    def delete_file(file)
        file= find_file(file)
        file.delete(true)
    end
    
    # 画像をStringでダウンロードする
    def download_file(file)
        file = find_file(file)
        @file_string = file.download_to_string()
    end
    
    # TODO exif情報のnilチェック
    def is_exif?(exif)
        exif.date_time_original!= nil or exif.gps_latitude != nil or exif.gps_longitude != nil
    end

    # 画像のメタ情報を取得
    def image_meta(exif)
        # 撮影日
        exif.date_time_original
         
        # 緯度、軽度
        if exif.gps_latitude != nil or exif.gps_longitude != nil
            latitude = (exif.gps_latitude[0].to_f + (exif.gps_latitude[1].to_f)/60 + (exif.gps_latitude[2].to_f)/3600).to_s
            longitude = (exif.gps_longitude[0].to_f + (exif.gps_longitude[1].to_f)/60 + (exif.gps_longitude[2].to_f)/3600).to_s
        end
         
        # 緯度軽度の結合
        location = [latitude,longitude].join(",")

        # 緯度経度から住所を取得
        Geocoder.configure(:language => :ja,:units => :km )
         
        response_geocoder = Geocoder.search(location)[0]
        full_address = response_geocoder.formatted_address
        
        address = response_geocoder.address_components
        if address[address.length - 1]['types'] = ["postalcode"]
            address.delete_at(-1)
        end
        address = address[address.length - 1 ]['long_name'] << 
                    address[address.length - 2 ]['long_name'] << 
                    address[address.length - 3 ]['long_name']
                    
        @image_meta = {
            :latitude     => latitude,
            :longitude    => longitude,
            :full_address => full_address,
            :address      => address
        }
    end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@edit_file) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="form-group">
            <%= f.label :comment ,"コメント"%>
            <%= f.text_area :comment, class: "form-control", placeholder: "300文字以下です" %>
          </div>
          <div class="submit-group">
            <%= f.submit "登録する", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
    </div>
    
</div>

app/views/images/new.html.erb
<div class="container">

<% flash.each do |type,msg|  %>
<div class="alert alert-danger">
  <%= flash[:danger] %> 
</div>
<% end %>

<%= form_tag( {action: :create}, multipart: true) do %>
    <%= flash[:alert] %>
    <%= file_field_tag :file %>
    <%= submit_tag "ファイルをアップロードする" ,class:"btn btn-default" %>
<% end %>

</div>

app/views/images/show.html.erb
<div class="container">
    <div class="center-block">
    <%= image_tag  url_for(:controller => 'images',:action=>'get_image', :id=> @show_file.id), class: "main_image"%>
    </div>
    <table class="table table-striped">
        <tbody>
            <tr>
                <th>撮影場所 </td>
                <td>
    <%= @show_file.full_address%>
                </td>
            </tr>
    
    <% if @show_file.comment != nil%>
            <tr>
                <th>コメント</td>
                <td>
        <%= @show_file.comment %>    
                </td>
            </tr>
    <% end %>
        </tbody>
    </table>

    <p><%= link_to "削除" , @show_file , method: :delete, data: { confirm: "You sure?" } %></p>
    <p><%= link_to "編集" ,edit_image_path %></p>
</div>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
    			<button type="button" class="navbar-toggle " data-toggle="collapse" data-target="#navbarEexample">
    				<span class="sr-only">Toggle navigation</span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    				<span class="icon-bar"></span>
    			</button>
    			<a><%= link_to "Photo-library", root_path  ,id:"logo"%></a>
  		  </div>
  
  
        <div class="collapse navbar-collapse" id="navbarEexample">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Images <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Upload Image",   new_image_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>

                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo-Library</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div id="map"></div>
<script type="text/javascript">
var map;
function initMap() {
map = new google.maps.Map(document.getElementById('map'), {
center: {lat: 38, lng: 138},
zoom: 6
});

<% @images.each_with_index do |image,i| %>
var infowindow<%= i %> = new google.maps.InfoWindow({
    content: '<p><%= image.address %></p><%= image_tag @google_images.find{|item| item.id == image.google_id}.thumbnail_link %>'

});

var marker<%= i %> = new google.maps.Marker({
position: {lat: <%= image.latitude.to_f %>, lng: <%= image.longitude.to_f %>},
map: map,
title: '<%= image.address %>'
});

marker<%= i %>.addListener('click', function() {
    infowindow<%= i %>.open(map, marker<%= i %>);
});
<% end %>


}
</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?callback=initMap">
</script>

app/views/users/_form.html.erb
<%= user.id %>

app/views/users/edit.html.erb
<div class="container">
<h1>Edit</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name ,"名前"%>
        <%= f.text_field :name, class: "form-control", placeholder: "10文字以下です" %>
      </div>
      <div class="form-group">
        <%= f.label :email , "メールアドレス"%>
        <%= f.text_field :email, class: "form-control", placeholder: "256文字以下です。" %>
      </div>
      <div class="form-group">
        <%= f.label :password , "パスワード" %>
        <%= f.password_field :password, class: "form-control", placeholder: "特に制限はありません" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "パスワード(確認用)" %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "もう一度入力をお願いします" %>
      </div>
      <div class="submit-group">
        <%= f.submit "登録する", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
</div>
</div>
</div>

app/views/users/new.html.erb
<div class="container">
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="form-group">
            <%= f.label :name ,"名前"%>
            <%= f.text_field :name, class: "form-control", placeholder: "10文字以下です" %>
          </div>
          <div class="form-group">
            <%= f.label :email , "メールアドレス"%>
            <%= f.text_field :email, class: "form-control", placeholder: "256文字以下です。" %>
          </div>
          <div class="form-group">
            <%= f.label :password , "パスワード" %>
            <%= f.password_field :password, class: "form-control", placeholder: "特に制限はありません" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "パスワード(確認用)" %>
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "もう一度入力をお願いします" %>
          </div>
          <div class="submit-group">
            <%= f.submit "登録する", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
    </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<h2><%= @user.name %></h2>
<% if @user == current_user %>
<%= link_to "写真をアップロード" , new_image_path, class: "btn btn-primary" %>
<hr/>
<% end %>

<% flash.each do |type,msg|  %>
<div class="alert alert-success">
  <%= flash[:success] %> 
</div>
<% end %>


<% if @user.images.any? %>
    <% @images.each do |image| %>
      <%= link_to  image_tag(@google_images.find{|item| item.id == image.google_id}.thumbnail_link), image,class: "thumbnail_image"%>
    <% end %>
<% end %>
</div>